### PR TITLE
Fix the flag of China stars rotating issue #11

### PR DESCRIPTION
**Pull request by tao-guo**
1. Create helper function to link polygen points.
2. Draw five angle stars with polygen() for css clip-path.

### CODE REVIEW

**Comment by pixelastic** [comment]
Whoo, thanks.

1. Could you explain the trick to combine several shapes into one `polygon` declaration? I have trouble following what the SCSS code is doing here.

2. Your way of drawing the star is way more elegant than mine. Thanks.

**Comment by tao-guo** [comment]
Thanks for reviewing. Basically you need to make sure each polygon is a loop, and you go from one loop to another and will eventually come back. The first loop point and last loop point can be skipped. 

I just got the inspiration from this link:  https://css-tricks.com/cutting-inner-part-element-using-clip-path/

**Comment by tao-guo** [comment]
```
    clip-path: polygon(
      0 50%, 40% 0, 40% 100%, 0 50%,
      100% 50%, 60% 0, 60% 100%, 100% 50%
      );
```
clip

```
    clip-path: polygon(
      0 0, 40% 0, 0 40%, 0 0,
      100% 0, 100% 40%, 60% 0, 100% 0,
      100% 100%, 60% 100%, 100% 60%, 100% 100%,
      0 100%, 0 60%, 40% 100%, 0 100%,
      100% 100%, 100% 0
      );
```
clip2

**Comment by pixelastic** [comment]
I'm in the process of merging it. Just want to understand how it works first so I can re-use it on other flags.

How did you get the angle values? Did you calculate them by hand or do you have construction cheet somewhere?

**Comment by tao-guo** [comment]
Yes, I calculated myself based on the spec on [wikipedia](https://en.wikipedia.org/wiki/Flag_of_China):
```bash
tguo@ln-tguo:/tmp/mozilla_tguo0$ node
> Math.atan(3/5)/Math.PI*180+90
120.96375653207352
```

**Pull request merged**
